android.enableJetifier=true
android.useAndroidX=true
# Jetifier with Robolectric transform fix:
# Add android.jetifier.blacklist=bcprov or android.enableJetifier=false to gradle.properties. or upgrade to 7.1.x of AGP (Android Gradle Plugin).
#android.jetifier.blacklist=bcprov
android.jetifier.ignorelist=bcprov
# Get ready for minification (NoSuchMethodError on kivi???)
#android.enableR8.fullMode=true
# Minification ram usage fix
#org.gradle.jvmargs=-Xmx1024m
android.suppressUnsupportedCompileSdk=34
android.disableAutomaticComponentCreation=true
org.gradle.java.home=C:/Program Files/Eclipse Adoptium/jdk-11.0.31.11-hotspot


# Temporary P12.4 recovery settings - restored after build
org.gradle.daemon=false
org.gradle.workers.max=1
org.gradle.parallel=false
org.gradle.vfs.watch=false
kotlin.compiler.execution.strategy=in-process
kotlin.daemon.enabled=false